//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarnetFileService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class filedev_varnetsolutions_dbEntities : DbContext
    {
        public filedev_varnetsolutions_dbEntities()
            : base("name=filedev_varnetsolutions_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MediaTable> MediaTables { get; set; }
    
        public virtual ObjectResult<sp_get_filepaths_by_media_ids_Result> sp_get_filepaths_by_media_ids(string mediaIds)
        {
            var mediaIdsParameter = mediaIds != null ?
                new ObjectParameter("MediaIds", mediaIds) :
                new ObjectParameter("MediaIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_filepaths_by_media_ids_Result>("sp_get_filepaths_by_media_ids", mediaIdsParameter);
        }
    }
}
