//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarnetFileService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaTable
    {
        public int id { get; set; }
        public string application_code { get; set; }
        public string tenant_code { get; set; }
        public string media_id { get; set; }
        public string mime_type { get; set; }
        public int file_size { get; set; }
        public string file_path { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> used_for { get; set; }
        public string file_url { get; set; }
        public int user_id { get; set; }
        public string ServiceCode { get; set; }
        public string file_nm { get; set; }
    }
}
